# Kad tave šikantį sutrauktų kas parasė šita šudina, nelankstų,
# toolą, po galais, rimtai negali lengvai parašyti savo projektui specifiškų
# taisyklių??? Velniai rautų...
AllCops:
  Exclude:
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'     
    - 'config/**/*'     
    - 'script/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.4

Style/SimplifyNotEmptyWithAny:
  Enabled: true

Metrics/MethodLength:   
  Max: 15

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false