# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 986c33e8f786af8972030ef314e36175c934e43141f36c5d906d57719941f64028d70644fccdb3a967ca467dc2ad1c22405ebe1c05e8100c3033803bf0fff714

test:
  secret_key_base: d9b1c5c24f1b225aa7f04944360755a45574c1db42fbc399447d7d515a6496f7c4531f424a9f4b10f8a837bd3ec281e3f79509622e0bc946225b295aa9652f1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
